### ISSUE TITLE
Editor freezes in Windows when a file changed

### ISSUE THREAD

**Issue by WeeJeWel** [printhom/devkit-core#39]
Reproduce:
1. Open a project
2. Change a file (delete, rename, whatever)

**Comment by WeeJeWel** [comment]
Correction: hangs. Takes a few minutes..

**Comment by ChrisTerBeke** [comment]
Why is this assigned to me?

**Comment by ChrisTerBeke** [comment]
Library issue, let's change to https://github.com/shama/gaze

**Comment by ChrisTerBeke** [comment]
fixed by using another watcher
