### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by geordieF** [printhom/devkit-core#43]
Does not say how, do I need bower, grunt etc

**Comment by WeeJeWel** [comment]
@geordieF this project is not maintained anymore

**Comment by geordieF** [comment]
ah

**Comment by ChrisTerBeke** [comment]
if you wanna continue fiddling with it, there's an install guide here (https://github.com/PRINTR3D/formide-devkit-gui) as well as in the atom version (both links in the Readme).
